### ISSUE TITLE
Docker on Synology x86 refuses to launch

### ISSUE THREAD

**Issue by BerndGewehr** [angelnu/docker-ccu#34]
I get this error when I try to run the container on a celeron-based Synology NAS:

`standard_init_linux.go:189: exec user process caused "exec format error"`

Any suggestions?

**Comment by angelnu** [comment]
You will need to prepare your NAS kernel to run arm binaries before stating the CCU: `docker run --rm --privileged multiarch/qemu-user-static:register --reset`

Since key components do not start a native x86 docker container is preferred. There is a version here: https://hub.docker.com/r/litti/dccu2-x86_64/ . It is not the latest but since I am not making progress with my own version is the only version available right now.

**Comment by nicx** [comment]
any progress with the x86 version? I would love it ;)

**Comment by angelnu** [comment]
Not here but maybe you can try https://hub.docker.com/r/litti/dccu2-x86_64/

I have not tried it myself since I have a dedicated ARM node in my K8S cluster for the homematic CCU.

**Comment by angelnu** [comment]
Version on x86 available - see https://github.com/jens-maus/RaspberryMatic/wiki/Docker
