### ISSUE TITLE
Documentation: Docker Hub

### ISSUE THREAD

**Issue by Fruchuxs** [angelnu/docker-ccu#43]
There is no documentation how to use the container from docker hub, or how to link the usb device to docker. There is many text in the readme, but nothing helpfull at all. I just want to use your great work.

**Comment by JackGruber** [comment]
Hi,

look into the **How to deploy**
https://github.com/angelnu/docker-ccu#how-to-deploy

You have to configure some parameters and then use the deploy script.

**Comment by Fruchuxs** [comment]
Thank you. But I got some problems. The Web GUI starts, but it seems that my HmIP-RFUSB doesn't work if I use my GPIO for other things (like my raspbee II).

In the docker logs I get these errors:
```
Starting /etc/init.d/S61rfd
Starting rfd: ........................................ERROR

Starting /etc/init.d/S62HMServer
Starting HMIPServer: (/dev/mmd_hmip) .......................................................................................................................................................ERROR
```

In /boot/config.txt I removed the line `dtoverlay=pivccu-raspberrypi`. Do I need this line for the HmIP-RFUSB?! If I interprete https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md correctly, this line is not needed.

**Comment by angelnu** [comment]
You should call the deploy.sh script which under the covers installs the required device drivers and prepare the corresponding docker command. The command is quite long due to 3 hw devices, a volume and multiple ports that are needed -> this is why I created and script.

The script also takes care of configuring the overlay if you run in a Linux supported by pyvccu - I use his packages for the host since it takes care of all the different HW.
