### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by stsirakidis** [angelnu/docker-ccu#47]
I have this docker image running on a RPi and the web GUI is so far on port 80.

What changes are needed to run it behind a reverse proxy? 

E.g. I have a nginx reverse proxy running and could proxy e.g. as:
```
  location /ccu/ {
    proxy_pass  http://ccu/;
    include     common_location.conf;
  }
```
and this would be like https://[fqdn]/ccu

**Comment by angelnu** [comment]
Sorry, I have no experience with reverse proxies since I use virtual hosts with Kubernetes ingress so the config is done there automatically for me.

Btw: closing issue since migrated to RaspberryMatic -> see https://github.com/jens-maus/RaspberryMatic/wiki/Docker

If issue is still there in RaspberryMatic please open an issue there - I will provide support there.
